services:
    sql:
        container_name: divblox-db
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: "[rootPassword]"
            MYSQL_USER: "[user]"
            MYSQL_PASSWORD: "[password]"
            MYSQL_DATABASE: "[database]"
        volumes:
            - dxsqldata:/var/lib/mysql
        ports:
            - [port]:3306
volumes:
    dxsqldata: {}
