version: 1'
services:
    sql:
        container_name: divblox-db
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_USER: "dxuser"
            MYSQL_PASSWORD: "secret"
            MYSQL_DATABASE: "dxdatabase"
        volumes:
            - dxsqldata:/var/lib/mysql
        ports:
            - 3307:3306
volumes:
    dxsqldata: {}
